<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Geldii Yer Arama Daire Bak</name>
   <tag></tag>
   <elementGuidId>5ace9e8e-461a-4433-b93b-b619fcfb082a</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainInboxForm:inboxDataTable:0:evrakTable&quot;)/tbody[1]/tr[@class=&quot;ui-widget-content&quot;]/td[@class=&quot;ui-inbox-satir2&quot;]/div[@class=&quot;searchText&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>styleclass</name>
      <type>Main</type>
      <value>tipTip</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Geldiği Yer: Arama Daire Başkanlığı / Saha Jeolojisi Müdürlüğü</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchText</value>
   </webElementProperties>
</WebElementEntity>
